#!/bin/bash

set -e

PARENT_PATH=$(dirname $(
  cd $(dirname $0)
  pwd -P
))

TARGET_TRIPLE=$(rustc -vV | sed -n 's|host: ||p')

pushd $PARENT_PATH
mkdir -p src-tauri/bin
GO111MODULE=on go build -ldflags="-s -w" -o src-tauri/bin/grpcproxy-$TARGET_TRIPLE rpc_proxy.go
popd
