#!/usr/bin/env bash

cd ./src/api-spec || exit
mkdir -p generated/js

GRPC_TOOLS_NODE_PROTOC="../../node_modules/.bin/grpc_tools_node_protoc"
GRPC_WEB_PLUGIN="../../node_modules/.bin/protoc-gen-grpc-web"

${GRPC_TOOLS_NODE_PROTOC} \
--js_out=import_style=commonjs,binary:./generated/js \
--grpc-web_out=import_style=typescript,mode=grpcwebtext:./generated/js \
--plugin=protoc-gen-grpc-web=${GRPC_WEB_PLUGIN} \
./*.proto
