#!/bin/bash

set -e

PARENT_PATH=$(dirname $(
  cd $(dirname $0)
  pwd -P
))

VENDOR=$(uname -s | tr '[:upper:]' '[:lower:]')


if [ "$VENDOR" == "darwin" ]
then
  OS=${VENDOR}
  VENDOR="apple"
fi

if [ "$VENDOR" == "linux" ]
then
  OS=gnu
  VENDOR="unknown-linux"
fi

pushd $PARENT_PATH
mkdir -p src-tauri/bin
GO111MODULE=on go build -ldflags="-s -w" -tags netgo -a -o src-tauri/bin/grpcproxy-x86_64-$VENDOR-$OS rpc_proxy.go
GO111MODULE=on go build -ldflags="-s -w" -tags netgo -a -o src-tauri/bin/grpcproxy-aarch64-$VENDOR-$OS rpc_proxy.go
GO111MODULE=on go build -ldflags="-s -w" -tags netgo -a -o src-tauri/bin/grpcproxy-aarch64-linux-android rpc_proxy.go
popd
