#!/usr/bin/env bash

# this script gets a list of files from raw.githubusercontent.com
# files will be stored in `api-spec`

declare -a files=(
    "https://raw.githubusercontent.com/tdex-network/tdex-protobuf/master/types.proto"
    "https://raw.githubusercontent.com/tdex-network/tdex-daemon/master/api-spec/protobuf/operator.proto"
    "https://raw.githubusercontent.com/tdex-network/tdex-daemon/master/api-spec/protobuf/walletunlocker.proto"
    "https://raw.githubusercontent.com/tdex-network/tdex-daemon/master/api-spec/protobuf/wallet.proto"
)

mkdir ./src/api-spec
cd ./src/api-spec || exit
rm -r ./*

for file in "${files[@]}"
do
    echo "downloading proto file: $file"
    wget -q "$file"
done

