#!/bin/bash

set -e

echo ""
echo "starting tdexd"

mkdir -p tdexd

docker-compose up -d oceand

docker run -it -d --name tdexd \
   -p 9945:9945 -p 9000:9000 \
   -v "$(pwd)/tdexd:/home/user/.tdex-daemon" \
   -e TDEX_NETWORK=regtest \
   -e TDEX_WALLET_ADDR=oceand:18000 \
   -e TDEX_EXPLORER_ENDPOINT=http://chopsticks-liquid:3000 \
   -e TDEX_LOG_LEVEL=5 \
   -e TDEX_FEE_ACCOUNT_BALANCE_THRESHOLD=1000 \
   -e TDEX_DB_HOST=tdexd-regtest-db \
   -e TDEX_NO_MACAROONS=true \
   -e TDEX_NO_OPERATOR_TLS=true \
   -e TDEX_CONNECT_PROTO=http \
   -e TDEX_DB_PORT=5433 \
   --network="nigiri" \
   ghcr.io/tdex-network/tdexd:v0.9.0-rc.0

echo ""
echo "init wallet"

tdex='docker exec -it tdexd tdex'
$tdex config init --no_macaroons --no_tls

mnemonic=$($tdex genseed | grep "\S")
$tdex init --seed "${mnemonic}" --password hellohello
