#!/bin/bash

set -e

echo ""
echo "starting tdexd"

mkdir -p tdexd

docker-compose up -d oceand

docker run -it -d --name tdexd \
  -p 9945:9945 -p 9000:9000 \
  -v "$(pwd)/tdexd:/home/user/.tdex-daemon" \
  -e TDEX_NETWORK=testnet \
  -e TDEX_WALLET_ADDR=oceand:18000 \
  -e TDEX_EXPLORER_ENDPOINT=https://blockstream.info/liquidtestnet/api \
  -e TDEX_LOG_LEVEL=5 \
  -e TDEX_FEE_ACCOUNT_BALANCE_THRESHOLD=1000 \
  -e TDEX_DB_HOST=tdexd-regtest-db \
  -e TDEX_NO_MACAROONS=false \
  -e TDEX_NO_OPERATOR_TLS=true \
  -e TDEX_CONNECT_PROTO=http \
  -e TDEX_DB_PORT=5433 \
  -e TDEX_CRAWL_INTERVAL=5000 \
  -e TDEX_CRAWL_LIMIT=5000 \
  -e TDEX_CRAWL_TOKEN=500 \
  -e TDEX_NETWORK=testnet \
  -e TDEX_EXPLORER_REQUEST_TIMEOUT=40000 \
  --network="nigiri" \
  ghcr.io/tdex-network/tdexd:v0.9.0-rc.1

echo ""
echo "init wallet"

tdex='docker exec -it tdexd tdex'
$tdex config init --network "testnet"

mnemonic=$($tdex genseed | grep "\S")
$tdex init --seed "${mnemonic}" --password ciaociao

echo ""
echo "unlocking wallet"

$tdex unlock --password ciaociao
